name: eatopia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  email_validator: ^2.1.17
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Ubuntu
    fonts:
    - asset: fonts/Ubuntu/Ubuntu-Light.ttf
  assets:
    - images/




